apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: lukasmichalcak/ambulance-ufe
  newName: lukasmichalcak/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260317.1609 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: lukasmichalcak/ambulance-wl-webapi
  newName: lukasmichalcak/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260331.1303 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
