apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm1234-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /lm1234-openapi
            - name: BASE_URL
              value: /lm1234-openapi-ui